### ISSUE TITLE
Deployment Guide for both Backend and Frontend

### ISSUE THREAD

**Issue by shiram** [bhangyiluke/DFCU#1]
Hi @bhangyiluke 
I have not been able to find the documentation for deploying the frontend and backend. Is it possible to have a README that describes the process.

Thank you.

**Comment by bhangyiluke** [comment]
Ok.
Let me work on the ReadMe file.

Regards,
Luke Bhangyi
M: +971501527673
*linkedin* <https://www.linkedin.com/in/luke-bhangyi-b292a139/> *github*
<https://github.com/bhangyiluke>

**Comment by bhangyiluke** [comment]
Hello @shiram 
Please see the readme file as requested and download the repository affresh. You can create a folder with my name _bhangyi_ and do _git clone https://github.com/bhangyiluke/DFCU.git ._  into that folder to download both the back-end and front-end.

Regards,
Luke Bhangyi
